### ISSUE TITLE
Refactorizar todo lo que ya llevamos hecho para mejor organización del código

### ISSUE THREAD

**Issue by danielomunoz** [danielomunoz/easyback.io#4]

**Comment by danielomunoz** [comment]
- [x] Hacer arrays todos los campos de la validación de las rutas
- [ ] Sacar los parámetros de las rutas al principio del tratamiento, según el campo validation o los fields, eso ahorrará mucho código.
- [x] Cambiar todos los bucles for por forEach
- [x] Externalizar todas las strings que contengan código, comentando el código bien estructurado e identado y dejándolo como una sola línea para cuando necesite incrustarse
- [x] Eliminar los steps de las routes. Que cada route sea un step en sí mismo. Priorizar las rutas por defecto sobre las introducidas por el usuario. Escribir todas las rutas por defecto para las tables, pero dar opción de sobreescribir la validación. Esto hará la template más sencilla y el desarrollo también.
